#!/bin/bash

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth-n

if [ ! -f "$XAUTH" ]
then
  xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge - > /dev/null 2>&1
fi

FILE_PATH=$@
DIR=$(dirname "${FILE_PATH}")
FILE=$(basename "${FILE_PATH}")

if [ "$DIR" = "." ]
then
  DIR=$(pwd)
fi

if [[ "$DIR" != /* ]]
then
 DIR="$(pwd)/$DIR"
fi

docker run \
 --rm \
 -ti \
 -v $XSOCK:$XSOCK \
 -v $XAUTH:$XAUTH \
 -e XAUTHORITY=$XAUTH \
 -e DISPLAY=$DISPLAY \
 -e UGID="$(id -u $USER):$(id -g $USER)" \
 -v="$HOME/.config/nvim:/root/.config/nvim" \
 -v="$HOME/.local/share/nvim/:/root/.local/share/nvim" \
 -v="$HOME/.fzf:/root/.fzf" \
 -v="$DIR:/workspace/$DIR" \
 -w="/workspace/$DIR" \
 hrcarsan/nvim:0.3.8 nvim $FILE
